language: node_js

addons:
  hosts:
    - relay.circles.local

services:
  - docker

node_js:
  - '10'

before_install:
  # install python version 2.7.15
  - pyenv install 2.7.15
  - pyenv global 2.7.15

  # disable travis postgres
  - sudo /etc/init.d/postgresql stop

  # get docker repository and configure it
  - git clone https://github.com/CirclesUBI/circles-docker.git
  - cd circles-docker
  - cp .env.example .env

  # containers setup via docker-compose
  - make build
  - make up
  - cd ..

  # core configuration
  - cp .env.example .env

install:
  - npm install

script:
  - npm run test
  - npm run build
