language: node_js

addons:
  hosts:
    - relay.circles.local

services:
  - docker

node_js:
  - '11'

before_install:
  # get latest pyenv version
  - cd $(pyenv root)
  - git fetch --all --tags --prune
  - git checkout tags/v1.2.13
  - cd -

  # install python version 2.7.15
  - pyenv install 2.7.15
  - pyenv global 2.7.15

  # disable travis postgres
  - sudo /etc/init.d/postgresql stop

  # install truffle
  - npm install -g truffle

  # get circles-docker repository and copy configs
  - git clone https://github.com/CirclesUBI/circles-docker.git
  - cd circles-docker
  - cp .env.example .env

  # container setup via docker-compose
  - make build
  - make up
  - cd ..

  # copy core configs
  - cp .env.example .env

install:
  - npm install

script:
  - npm run test
  - npm run build
